
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'test/integration/capabilities/serverspec/capabilities_drop_spec.rb'

Lint/DuplicatedKey:
  Exclude:
    - 'libraries/helpers.rb'

Lint/UnreachableCode:
  Exclude:
    - 'providers/altdisk.rb'

Lint/UselessAssignment:
  Exclude:
    - 'providers/altdisk.rb'
    - 'providers/chsec.rb'
    - 'providers/nimclient.rb'
    - 'providers/no.rb'
    - 'providers/tunables.rb'

Metrics/BlockNesting:
  Max: 5

Style/AccessorMethodName:
  Exclude:
    - 'providers/altdisk.rb'

# Cop supports --auto-correct.
# Configuration parameters: Keywords.
# Keywords: TODO, FIXME, OPTIMIZE, HACK, REVIEW
Style/CommentAnnotation:
  Exclude:
    - 'resources/subserver.rb'

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'providers/nimclient.rb'
    - 'providers/volume_group.rb'

Style/IdenticalConditionalBranches:
  Exclude:
    - 'providers/etchosts.rb'

# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Style/PredicateName:
  Exclude:
    - 'providers/nimclient.rb'
